version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5440:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-task-maksim-gavriliuk
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_PASSWORD=root
    depends_on:
      - postgres
    ports:
      - '8080:8080'