spring:
  datasource:
    username: root
    password: maksi
    url: jdbc:postgresql://localhost:5432/test_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: debug
